# P4

In [8]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [9]:
%autoreload 2
from src import eliminacion_gaussiana, gauss_jordan
las funciones se encuentran disponibles como referencia

SyntaxError: invalid syntax (1611861752.py, line 3)

In [ ]:
import logging
from sys import stdout
from datetime import datetime
import numpy as np

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s][%(levelname)s] %(message)s",
    stream=stdout,
    datefmt="%m-%d %H:%M:%S",
)
logging.info(datetime.now())

[08-14 08:28:48][INFO] 2024-08-14 08:28:48.388372


In [ ]:
# ####################################################################
def gauss_jordan(Ab: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de Gauss-Jordan.

    ## Parameters

    ``Ab``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: matriz aumentada transformada.

    """
    if not isinstance(Ab, np.ndarray):
        logging.debug("Convirtiendo Ab a numpy array.")
        Ab = np.array(Ab)
    assert Ab.shape[0] == Ab.shape[1] // 2, "La matriz Ab debe ser de tamaño n-by-2n."
    n = Ab.shape[0]

    for i in range(n):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if Ab[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(Ab[pi, i]) < abs(Ab[p, i]):
                p = pi

        if p is None:
        
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            logging.debug(f"Intercambiando filas {i} y {p}")
            Ab[[i, p], :] = Ab[[p, i], :]

        # --- Eliminación: loop por fila
        for j in range(n):
            if i == j:
                continue
            m = Ab[j, i] / Ab[i, i]
            Ab[j, :] = Ab[j, :] - m * Ab[i, :]

        logging.info(f"\n{Ab}")

    if Ab[n - 1, n - 1] == 0:
        raise ValueError("No existe solución única.")

    return Ab

In [ ]:
%autoreload 2
from src import matriz_aumentada

A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
b = [1, -2, 3, 4]

Ab = matriz_aumentada(A, b)
gauss_jordan(Ab)

In [ ]:
# ####################################################################
def inv_matrix(A: np.ndarray) -> np.ndarray:
    """Inversión de una matriz cuadrada mediante el método de Gauss-Jordan.

    ## Parameters
    ``A``: matriz cuadrada de tamaño n x n.

    ## Return
    ``A_inv``: matriz inversa de A.
    """
    if not isinstance(A, np.ndarray):
        logging.debug("Convirtiendo A a numpy array.")
        A = np.array(A)
    assert A.shape[0] == A.shape[1], "La matriz A debe ser cuadrada."

    n = A.shape[0]
    
    I = np.eye(n)
    
    Ab = np.hstack((A, I))
    
    Ab_gauss = gauss_jordan(Ab)
    
  
    A_inv = Ab_gauss[:, n:]

    return A_inv


## Ejemplos 
Compruebe su función con respecto a los siguientes ejemplos:
* Ejemplo 1

In [ ]:
# La matriz A =
A = [
    [1, 2, 3, 4],
    [2, 5, 6, 7],
    [3, 6, 8, 9],
    [4, 7, 9, 10],
]
# tiene como inversa
# A_inv =[[ 0.5, -0.5, -1.5,  1.5],
#        [-0.5,  1.5, -1.5,  0.5],
#        [-1.5, -1.5,  3.5, -1.5],
#        [ 1.5,  0.5, -1.5,  0.5]]
inv_matrix(A)

[08-14 08:27:38][INFO] 
[[ 1.  2.  3.  4.  1.  0.  0.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0. -1. -3. -6. -4.  0.  0.  1.]]
[08-14 08:27:38][INFO] 
[[ 1.  0.  3.  6.  5. -2.  0.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0.  0. -3. -7. -6.  1.  0.  1.]]
[08-14 08:27:38][INFO] 
[[ 1.  0.  0. -3. -4. -2.  3.  0.]
 [ 0.  1.  0. -1. -2.  1.  0.  0.]
 [ 0.  0. -1. -3. -3.  0.  1.  0.]
 [ 0.  0.  0.  2.  3.  1. -3.  1.]]
[08-14 08:27:38][INFO] 
[[ 1.   0.   0.   0.   0.5 -0.5 -1.5  1.5]
 [ 0.   1.   0.   0.  -0.5  1.5 -1.5  0.5]
 [ 0.   0.  -1.   0.   1.5  1.5 -3.5  1.5]
 [ 0.   0.   0.   2.   3.   1.  -3.   1. ]]


array([[ 0.5, -0.5, -1.5,  1.5],
       [-0.5,  1.5, -1.5,  0.5],
       [ 1.5,  1.5, -3.5,  1.5],
       [ 3. ,  1. , -3. ,  1. ]])

* Ejemplo 2

In [ ]:
# La matriz A =
A = [
    [4, 4, 5, 1],
    [3, 4, 2, 2],
    [2, 1, 4, 1],
    [3, 2, 5, 4],
]
# tiene como inversa
# A_inv =[[-34.,  31.,  52., -20.],
#         [ 19., -17., -29.,  11.],
#         [ 12., -11., -18.,   7.],
#         [  1.,  -1.,  -2.,   1.]]
inv_matrix(A)

[08-14 08:27:47][INFO] 
[[ 2.   1.   4.   1.   0.   0.   1.   0. ]
 [ 0.   2.5 -4.   0.5  0.   1.  -1.5  0. ]
 [ 0.   2.  -3.  -1.   1.   0.  -2.   0. ]
 [ 0.   0.5 -1.   2.5  0.   0.  -1.5  1. ]]
[08-14 08:27:47][INFO] 
[[  2.    0.    6.   -4.    0.    0.    4.   -2. ]
 [  0.    0.5  -1.    2.5   0.    0.   -1.5   1. ]
 [  0.    0.    1.  -11.    1.    0.    4.   -4. ]
 [  0.    0.    1.  -12.    0.    1.    6.   -5. ]]
[08-14 08:27:47][INFO] 
[[  2.    0.    0.   62.   -6.    0.  -20.   22. ]
 [  0.    0.5   0.   -8.5   1.    0.    2.5  -3. ]
 [  0.    0.    1.  -11.    1.    0.    4.   -4. ]
 [  0.    0.    0.   -1.   -1.    1.    2.   -1. ]]
[08-14 08:27:47][INFO] 
[[  2.    0.    0.    0.  -68.   62.  104.  -40. ]
 [  0.    0.5   0.    0.    9.5  -8.5 -14.5   5.5]
 [  0.    0.    1.    0.   12.  -11.  -18.    7. ]
 [  0.    0.    0.   -1.   -1.    1.    2.   -1. ]]


array([[-68. ,  62. , 104. , -40. ],
       [  9.5,  -8.5, -14.5,   5.5],
       [ 12. , -11. , -18. ,   7. ],
       [ -1. ,   1. ,   2. ,  -1. ]])

# Ejercicios
* Ejercicio 1

In [ ]:
A = [
    [4, 0, 0, 5],
    [1, 0, 4, 0],
    [3, 4, 1, 3],
    [1, 3, 3, 0],
]
inv_matrix(A)

[08-14 08:27:50][INFO] 
[[  1.   0.   4.   0.   0.   1.   0.   0.]
 [  0.   0. -16.   5.   1.  -4.   0.   0.]
 [  0.   4. -11.   3.   0.  -3.   1.   0.]
 [  0.   3.  -1.   0.   0.  -1.   0.   1.]]
[08-14 08:27:50][INFO] 
[[  1.           0.           4.           0.           0.
    1.           0.           0.        ]
 [  0.           3.          -1.           0.           0.
   -1.           0.           1.        ]
 [  0.           0.          -9.66666667   3.           0.
   -1.66666667   1.          -1.33333333]
 [  0.           0.         -16.           5.           1.
   -4.           0.           0.        ]]
[08-14 08:27:50][INFO] 
[[ 1.          0.          0.          1.24137931  0.          0.31034483
   0.4137931  -0.55172414]
 [ 0.          3.          0.         -0.31034483  0.         -0.82758621
  -0.10344828  1.13793103]
 [ 0.          0.         -9.66666667  3.          0.         -1.66666667
   1.         -1.33333333]
 [ 0.          0.          0.          0.034482

array([[ -36.        ,   45.        ,   60.        ,  -80.        ],
       [   9.        ,  -12.        ,  -15.        ,   21.        ],
       [ -87.        ,  106.33333333,  145.        , -193.33333333],
       [   1.        ,   -1.24137931,   -1.65517241,    2.20689655]])

* Ejercicio 2

In [ ]:
A = [
    [0, 0, 0, 0, 0, 0, 1, -1],
    [0, 1, -1, 1, 0, -1, 0, 1],
    [-1, -1, 0, 0, 2, 1, 0, 0],
    [-1, -1, -1, 1, 2, 0, 0, 1],
    [-1, 1, 1, 0, -1, -1, 0, 2],
    [0, 1, 0, 0, -1, -1, 0, 0],
    [1, -1, -1, 1, 2, 1, 0, 2],
    [2, 0, 0, 0, 0, 1, 2, 0],

]
inv_matrix(A)

NameError: name 'inv_matrix' is not defined

* Ejercicio 3

In [ ]:
A = [
    [1, 0, 0, 0, -1, 0, 0, -1, 1, -1],
    [1, 1, 0, -1, -1, 1, 0, 0, 1, -1],
    [-1, 0, -1, 0, 0, 0, -1, 1, 0, 0],
    [0, 0, -1, 0, -1, -1, 1, 0, 1, 0],
    [-1, 0, 0, -1, 1, 1, 1, 1, 0, -1],
    [1, 0, 0, 1, -1, -1, -1, 1, -1, 0],
    [1, 1, 1, 0, 1, 0, -1, -1, -1, 1],
    [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
    [1, 1, 1, 1, 1, 0, -1, -1, 0, 0],
    [0, 0, -1, -1, -1, 0, 1, 1, 1, -1],
]
inv_matrix(A)

[08-14 08:28:01][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1.  0.  1.  0.  1.  0.  0. -1.  1.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1.  0. -1.  0.  1. -1.  1.  0.  1.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0. -1.  0. -1. -1.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0. -1.  0.  1.  1.  0.  1. -2.  1.  0.  0.  0.  1.  0.  0.  0.
   0.  0.]
 [ 0.  0.  0.  1.  0. -1. -1.  2. -2.  1. -1.  0.  0.  0.  0.  1.  0.  0.
   0.  0.]
 [ 0.  1.  1.  0.  2.  0. -1.  0. -2.  2. -1.  0.  0.  0.  0.  0.  1.  0.
   0.  0.]
 [ 0.  1.  1.  1.  1.  0.  1.  2. -1.  1. -1.  0.  0.  0.  0.  0.  0.  1.
   0.  0.]
 [ 0.  1.  1.  1.  2.  0. -1.  0. -1.  1. -1.  0.  0.  0.  0.  0.  0.  0.
   1.  0.]
 [ 0.  0. -1. -1. -1.  0.  1.  1.  1. -1.  0.  0.  0.  0.  0.  0.  0.  0.
   0.  1.]]
[08-14 08:28:01][INFO] 
[[ 1.  0.  0.  0. -1.  0.  0. -1.  1. -1.  1.  0.  0.  0.  0.  0.  0.  0.
   0.  0.]
 [ 0.  1.  0. -1

array([[ 14. ,  -8. ,   9. ,  -4. ,   0. ,  -4. ,   9. ,   7. ,  -8. ,
          3. ],
       [ -2. ,   2. ,  -1. ,   2. ,   1. ,   1. ,  -1. ,  -1. ,   1. ,
         -2. ],
       [ 27. , -14. ,  18. ,  -5. ,   2. ,  -7. ,  17. ,  13. , -16. ,
          2. ],
       [-12. ,   6. ,  -8. ,   2. ,  -1. ,   3. ,  -7. ,  -6. ,   7. ,
          0. ],
       [  6. ,  -4. ,   4. ,  -2. ,   0. ,  -2. ,   4. ,   3. ,  -3. ,
          2. ],
       [-18. ,   9. , -12. ,   4. ,  -1. ,   5. , -11. ,  -9. ,  11. ,
         -1. ],
       [ -8. ,   4. ,  -5. ,   1. ,  -1. ,   2. ,  -5. ,  -4. ,   5. ,
          0. ],
       [-10. ,   4. ,  -6. ,   0. ,  -2. ,   2. ,  -6. ,  -4. ,   6. ,
          2. ],
       [ -5.5,   2.5,  -3.5,   0.5,  -1. ,   1. ,  -3.5,  -2.5,   3.5,
          0.5],
       [  1. ,  -1. ,   1. ,  -1. ,  -1. ,  -1. ,   1. ,   1. ,  -1. ,
          1. ]])